name: Monstrum2D!
version:
  major: 0
  minor: 1
fps: 30.0
ecs:
  component:
    - schemas: assets/game/gameplay_components.yaml
  system:
    - declaration: assets/game/gameplay.py
    - declaration: assets/game/render.py
    - declaration: assets/game/map_generator.py
    - declaration: assets/game/brute.py